Enable bitcoin_hashes v0.14.0
rust-bitcoin/rust-bip39 pull request #76
Opened 2024-07-30 21:58 UTC by tcharding

Hardware devices like the smallest binary possible, currently if one builds with latest `rust-bitcoin` and `rust-bip39` they get two versions of `bitcoin_hashes` in the dependency graph because we don't support the latest `bitcoin_hashes`.

We use a range dependency for `bitcoin_hashes`. We can support the latest version with no code changes. However using the latest version causes the MSRV to increase.

Add the latest version of `bitcoin_hashes` to the range dependency.

2024-07-30 21:59 UTC, tcharding commented
cc @afilini

2024-07-31 19:03 UTC, afilini commented
ACK, that would be helpful for me, all the other libs like rust-bitcoin and bdk have already upgraded to hashes 0.14

2024-08-26 12:04 UTC, Kixunil requested changes
This would be nice for me even just for cleanness sake.

2024-08-26 12:04 UTC, Kixunil commented on Cargo.toml
> +bitcoin_hashes = ">=0.12,<=0.14" # enable default features for test
This must be `>= 0.12, <0.15`, otherwise 0.14.1 will be unusable even though it'd be compatible.

2024-08-26 12:04 UTC, Kixunil commented on Cargo.toml
> +bitcoin_hashes = { version = ">=0.12, <=0.14", default-features = false }
This also needs to be `<0.15`, it was already broken.

2024-08-26 23:18 UTC, tcharding commented on Cargo.toml
> +bitcoin_hashes = ">=0.12,<=0.14" # enable default features for test
Oh wow, TIL. Will fix, thanks.

2024-08-26 23:18 UTC, tcharding commented on Cargo.toml
> +bitcoin_hashes = ">=0.12,<=0.14" # enable default features for test
I'm going to go right ahead and 'trust don't verify'.

2024-08-27 08:13 UTC, Kixunil approved these changes
ACK 2b47d406e1230c6ea6373efe6213f254e69af54a

2024-08-27 08:15 UTC, Kixunil commented on Cargo.toml
> +bitcoin_hashes = ">=0.12,<=0.14" # enable default features for test
The verification is easy, just evaluate `0 < 1` expression in your head. :)

2024-08-28 23:51 UTC, tcharding commented on Cargo.toml
> +bitcoin_hashes = ">=0.12,<=0.14" # enable default features for test
Oh I thought we were talking about `0.14` working for `0.14.0` but not for `0.14.1`.

2024-08-29 06:58 UTC, Kixunil commented on Cargo.toml
> +bitcoin_hashes = ">=0.12,<=0.14" # enable default features for test
0.14 implies 0.14.0

2024-08-29 09:14 UTC, tcharding commented on Cargo.toml
> +bitcoin_hashes = ">=0.12,<=0.14" # enable default features for test
Ok, I have no idea what you were talking about in your original comment then. `<= 14` is equivalent to `< 15`

2024-08-29 09:24 UTC, Kixunil commented on Cargo.toml
> +bitcoin_hashes = ">=0.12,<=0.14" # enable default features for test
It's not. 0.14 == 0.14.0
0.14.1 > 0.14.0
0.14.1 < 0.15.0
And the above implies 0.14.1 > 0.14 which is a negation of `0.14.1 <= 0.14`
So for `<= 14` to be equivalent to `< 15` we require all `x` to satisfy `x <= 0.14 <-> x <0.15` and we have a counter example for `x = 0.14.1`. QED

2024-08-29 19:48 UTC, tcharding commented on Cargo.toml
> +bitcoin_hashes = ">=0.12,<=0.14" # enable default features for test
> Oh I thought we were talking about 0.14 working for 0.14.0 but not for 0.14.1.

That is exactly what I meant when I said this, hence my confusion :)

2024-08-29 19:51 UTC, tcharding commented on Cargo.toml
> +bitcoin_hashes = ">=0.12,<=0.14" # enable default features for test
Thanks for clarifying though man.

2024-08-29 19:54 UTC, tcharding commented on Cargo.toml
> +bitcoin_hashes = ">=0.12,<=0.14" # enable default features for test
I get it now. Seems the confusion started when I wrote "I'm going to go right ahead and 'trust don't verify'." and I have no clue what I was thinking then. Your original review comment is actually perfectly clean.

Just call me retarded :)

2024-08-29 19:56 UTC, tcharding commented
Oh this PR is no good anyway, `bitcoin_hashes v14` has an incompatible MSRV.

2024-09-18 04:33 UTC, tcharding commented
Raised #79 to discuss the MSRV bump. Converting to draft until that resolves.

2025-02-04 11:07 UTC, kayabaNerve commented
Is this a MSRV bump? Anyone who wants an older MSRV can use an older version of bitcoin_hashes. This may cause some automated workflows to fail on first pass? But I wouldn't consider that breaking, as at worst it  would be trivially correctable by an extra line in a `Cargo.toml` of `bitcoin_hashes = "=0.12"`

2025-02-04 11:20 UTC, Kixunil commented
@kayabaNerve that line wouldn't be great, better jut use `Cargo.lock` correctly.

2025-02-04 15:11 UTC, Kixunil commented
> Precise updates get overriden upon the next call to update.

MSRV doesn't get bumped on update if you use recent cargo. But yes, this is not MSRV break in the sense that it'd justify major version.

2025-08-20 08:53 UTC, benma commented
Could you take this PR out of draft and merge and release please? :smile: Seems like a simple change and I need it for the reason @tcharding outlined.

2025-08-28 15:52 UTC, dmitrmax commented
> Could you take this PR out of draft and merge and release please? 😄 Seems like a simple change and I need it for the reason @tcharding outlined.

I second this. The simplest fix is resting on the shelf for more than a year now.

Maintainer, please do the v2.2.1 release.

2025-09-03 08:38 UTC, benma commented
Ping @tcharding @stevenroose, please let's merge, it's a simple change and very much needed. Thanks

2025-09-04 02:55 UTC, tcharding commented
I'm not a maintainer here sorry mate. If you have a direct link to Steven you could hassle him.

2025-09-21 07:00 UTC, benma commented
@tcharding I guess the first step would be for you to rebase it (there are conflicts) and take it out of draft.

2025-09-21 23:01 UTC, tcharding commented
No sweat, done.

2025-09-21 23:07 UTC, tcharding commented
Oh this cannot be undrafted because of the MSRV bump. At the risk of being rude, and @stevenroose you can slap me in person when you see me next, I'd suggest one of the following:

 - Someone pester Steven to maintain his lib (I'm not going to do this, I've hassled him enough about other libs more important to me).
 - Suggest to him to bring on another maintainer, or offer to be one.
 - Fork the crate and sort it out.

I'm not the don of the rust-bitcoin org but I do feel in someway responsible that we have crates in the org that are not maintained. I don't know the solution to that problem.

No one is required to do anything round here, so props to Steven for writing the crate, and all due respect.

2025-10-26 22:37 UTC, tcharding commented
We have @tnull as a crate owner on crates.io now. And if my private conversation with @stevenroose is correct then @elsirion has been invited to be a crate owner also. I assume both of you were also given merge perms here so this PR should be able to make some progress now please.

2025-10-27 08:32 UTC, elsirion commented
I don't have merge perms or an crates.io invite yet as far as I can tell. Happy to take on the responsibility, but also respect if @stevenroose doesn't want too many people as maintainers.

2025-10-27 09:58 UTC, tnull commented on README.md
> -When using older version of Rust, you might have to pin the versions of several crates, for an up-to-date list refer to [`contrib/test.sh`](contrib/test.sh):
Why is this no longer true, i.e., why don't we have to pin back the other dependencies below?

2025-10-27 10:38 UTC, stevenroose approved these changes
Nice

2025-10-27 11:38 UTC, elsirion commented on README.md
> -When using older version of Rust, you might have to pin the versions of several crates, for an up-to-date list refer to [`contrib/test.sh`](contrib/test.sh):
Possibly a faulty rebase conflict resolution? I made changes to these lines in #86 and this PR was open forever. @tcharding

2025-10-27 11:41 UTC, elsirion submitted a review, later dismissed
Would like to clarify if the `README.md` changes were intentional before merging, I have a strong suspicion that they weren't and the described pinning isn't sufficient.

2025-10-27 20:49 UTC, tcharding commented on README.md
> -When using older version of Rust, you might have to pin the versions of several crates, for an up-to-date list refer to [`contrib/test.sh`](contrib/test.sh):
Oh I just clobbered them because over the last year (since edition 2018 came into rust-bitcoin) I've barely ever had to pin anymore. Admittedly not the best reason for the change, I've put it back how it was.

2025-10-27 20:53 UTC, tcharding commented
> I don't have merge perms or an crates.io invite yet as far as I can tell. Happy to take on the responsibility, but also respect if @stevenroose doesn't want too many people as maintainers.

@apoelstra can you add @elsirion and @tnull as a maintainers please. @stevenroose has confirmed this by signal message with me. He has added them both as owners on crates.io already. @tnull said he would message you directly on signal also about this.

For anyone reading @stevenroose does not check GitHub notifications so will likely not read this message any time soon. You'll just have to believe me that I talked with him.

https://crates.io/crates/bip39

2025-10-27 20:54 UTC, tcharding commented
> Hey Tobin! Talked to Steven and it seems he can't add me as an owner of the bip39 crate on Github as it's part of the org now. Could you add me and elsirion?

This via signal from @tnull to me.

2025-10-27 22:12 UTC, elsirion commented on README.md
> -When using older version of Rust, you might have to pin the versions of several crates, for an up-to-date list refer to [`contrib/test.sh`](contrib/test.sh):
I think it depends which MSRV you are targeting, a lot of the bip39 deps seem to have bumped their MSRV in minor version releases. I only had to pin for the old rust version tests back then.

2025-10-27 23:22 UTC, tcharding commented
> Docs were fixed, still need to test MSRV though, so no full ACK yet.

Good eye, thanks. I've added 4 MSRV jobs which is pretty ugly but should get the coverage we want.

2025-10-28 08:43 UTC, tnull commented
> > I don't have merge perms or an crates.io invite yet as far as I can tell. Happy to take on the responsibility, but also respect if @stevenroose doesn't want too many people as maintainers.
> 
> @apoelstra can you add @elsirion and @tnull as a maintainers please. @stevenroose has confirmed this by signal message with me. He has added them both as owners on crates.io already. @tnull said he would message you directly on signal also about this.
> 
> For anyone reading @stevenroose does not check GitHub notifications so will likely not read this message any time soon. You'll just have to believe me that I talked with him.
> 
> https://crates.io/crates/bip39

Can confirm I was added now.

2025-10-28 08:58 UTC, tnull reviewed
Mostly looks good, one nit, one comment.

2025-10-28 08:58 UTC, tnull commented on README.md
> +
nit: Spurious whitespace here.

2025-10-28 08:58 UTC, tnull commented on contrib/test.sh
> +if cargo --version | grep "1\.48"; then
No super strong opinion, but in LDK we use such a pattern (just an example, see https://github.com/lightningdevkit/rust-lightning/blob/0.2/ci/ci-tests.sh):

```bash
RUSTC_MINOR_VERSION=$(rustc --version | awk '{ split($2,a,"."); print a[2] }')

# The backtrace v0.3.75 crate relies on rustc 1.82
[ "$RUSTC_MINOR_VERSION" -lt 82 ] && cargo update -p backtrace --precise "0.3.74" --verbose
```

Seems this could be a bit cleaner/less error prone if we start handling even more different rust versions.

2025-10-28 09:19 UTC, elsirion commented on contrib/test.sh
> +if cargo --version | grep "1\.48"; then
I just hope that once we hit rust version `1.480` in 45 years we won't be testing `1.48` anymore :laughing:

2025-10-28 09:50 UTC, elsirion commented
LGTM, just some syntax errors in the workflow file

<img width="3459" height="401" alt="Screenshot 2025-10-28 at 05-49-43 Enable `bitcoin_hashes v0 14 0` · rust-bitcoin_rust-bip39@b3f9c4d" src="https://github.com/user-attachments/assets/34d5a876-b2da-46c8-8b5e-feabef7b4214" />

2025-10-28 13:23 UTC, apoelstra commented on README.md
> -When using older version of Rust, you might have to pin the versions of several crates, for an up-to-date list refer to [`contrib/test.sh`](contrib/test.sh):
In rust-bitcoin and related crates we've avoided pinning by using fixed lockfiles, which we basically never update even though we should. That's why you haven't had to deal with this crap @tcharding.

2025-10-28 13:35 UTC, tnull commented on README.md
> -When using older version of Rust, you might have to pin the versions of several crates, for an up-to-date list refer to [`contrib/test.sh`](contrib/test.sh):
Yeah, eventually we might want to discuss doing a conservative MSRV bump here (1.41 seems very old by now, for every standard), potentially just aligning it with the `rust-bitcoin` policy. 

But, for now, that's out-of-scope of this PR. And if we already have the checks in place, there probably is no rush to do so.

2025-10-28 22:57 UTC, tcharding commented
Used new syntax as suggested and fixed up the github action job names.

2025-10-28 23:24 UTC, tcharding commented
And used valid Rust versions, will fix pinning ...

2025-10-30 10:25 UTC, tnull reviewed
Seems CI is still broken due to dependency/pinning foo.

2025-11-05 04:23 UTC, tcharding commented
Is any one waiting on this that wants to work it out? I f**king hate pinning.

2025-11-05 10:41 UTC, tnull commented
> Is any one waiting on this that wants to work it out? I f**king hate pinning.

Hmm, honestly not so much the actual changes, but having the additional CI coverage would be nice. But no huge rush rn.

2025-11-05 11:09 UTC, elsirion commented on .github/workflows/.#rust.yml
> +tobin@pantera.283300:1761534469
Is this included by accident?

2025-11-05 23:54 UTC, tcharding commented
Instead of pinning I found a lock file that works for 1.41 and 1.48 and committed those, then used the 1.48 lock file for all the MSRV versions tested.

2025-11-06 09:40 UTC, tnull reviewed
> Instead of pinning I found a lock file that works for 1.41 and 1.48 and committed those, then used the 1.48 lock file for all the MSRV versions tested.

Hmm, not quite sure if I prefer that approach, especially given that we point users to `test.sh` for pinning instructions to make this work under a specific MSRV. And now, we don't pin there. If you prefer not to deal with the the pinning part, we can just land this (maybe only the first commit)? And I can take it from there.

2025-11-06 09:40 UTC, tnull commented on README.md
>  When using older version of Rust, you might have to pin the versions of several crates, for an up-to-date list refer to [`contrib/test.sh`](contrib/test.sh):
We refer here to `test.sh` for pinning instructions, and now there aren't any anymore.

2025-11-06 21:06 UTC, tcharding commented on README.md
>  When using older version of Rust, you might have to pin the versions of several crates, for an up-to-date list refer to [`contrib/test.sh`](contrib/test.sh):
Oh dear, good eye. Thanks man, ~will fix.~

2025-11-06 21:11 UTC, tcharding commented
> If you prefer not to deal with the the pinning part, we can just land this (maybe only the first commit)? And I can take it from there.

Great, I have zero interest in pinning or in this crate at all so I"d really appreciate not having to touch this PR anymore. Thanks for the offer. I've remove the second patch.

2025-11-07 07:51 UTC, tnull reviewed
Okay, LGTM mod one comment regarding the added `pins.sh`.

Can revisit extending MSRV test coverage in CI as a follow-up sometime.

2025-11-07 07:51 UTC, tnull commented on pins.sh
Seems this file isn't used anywhere? Can we drop it for now?

2025-11-09 20:56 UTC, tcharding commented on pins.sh
Bother, that was just supposed to be use while I was messing with the pinning. My bad. Removed.

2025-11-10 08:39 UTC, tnull approved these changes

2025-11-10 08:39 UTC, tnull commented on README.md
> +
This whitespace could still be dropped, but shouldn't block this PR :>

2025-11-10 23:21 UTC, tcharding commented
My bad, done.

2025-11-10 23:21 UTC, tcharding commented
I actually checked by diff this time ...

2025-11-11 21:43 UTC, elsirion approved these changes

2025-11-11 21:43 UTC, elsirion commented on README.md
> +- `bitcoin_hashes v0.14`: MSRV v1.56.0
I haven't verified this claim given that we decided to forgo CI checks for now and manually figuring out the necessary pinning is a pita. It seems benign enough and a reasonable assumption that the MSRV will be dictated by `bitcoin_hashes` and there aren't any further interactions in the code base.

2025-11-13 08:58 UTC, merged